//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectForWork {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CryptoForm {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CryptoForm() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ProjectForWork.CryptoForm", typeof(CryptoForm).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Point, аналогичного {X=12,Y=12}.
        /// </summary>
        internal static System.Drawing.Point button2_Location {
            get {
                object obj = ResourceManager.GetObject("button2.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Size, аналогичного {Width=136, Height=51}.
        /// </summary>
        internal static System.Drawing.Size button2_Size {
            get {
                object obj = ResourceManager.GetObject("button2.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Int32, аналогичного 12.
        /// </summary>
        internal static int button2_TabIndex {
            get {
                object obj = ResourceManager.GetObject("button2.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Main menu.
        /// </summary>
        internal static string button2_Text {
            get {
                return ResourceManager.GetString("button2.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Font, аналогичного [Font: Name=Mongolian Baiti, Size=10,8, Units=3, GdiCharSet=1, GdiVerticalFont=False].
        /// </summary>
        internal static System.Drawing.Font CryptoBox_Font {
            get {
                object obj = ResourceManager.GetObject("CryptoBox.Font", resourceCulture);
                return ((System.Drawing.Font)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Point, аналогичного {X=12,Y=86}.
        /// </summary>
        internal static System.Drawing.Point CryptoBox_Location {
            get {
                object obj = ResourceManager.GetObject("CryptoBox.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Boolean, аналогичного True.
        /// </summary>
        internal static bool CryptoBox_Multiline {
            get {
                object obj = ResourceManager.GetObject("CryptoBox.Multiline", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Size, аналогичного {Width=1874, Height=897}.
        /// </summary>
        internal static System.Drawing.Size CryptoBox_Size {
            get {
                object obj = ResourceManager.GetObject("CryptoBox.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Int32, аналогичного 13.
        /// </summary>
        internal static int CryptoBox_TabIndex {
            get {
                object obj = ResourceManager.GetObject("CryptoBox.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
    }
}
